#include "stm32f0_usart.h"
#include "stm32f0_peripheral.h"


/////////////////////////////////////////////////////////////////


void USART2_Com_Init(void)
{
    NVIC_InitTypeDef  NVIC_TEMP;
    
    RCC->GPIO_CLKREG |= USART2Com_GPIO_CLOCK_EN;
    RCC->USART2Com_CLKREG |= USART2Com_CLOCK_EN;
    
    
    USART2Com_TX_GPIOX->AFR[USART2Com_TX_PIN>>3] &= ~(0xf << ((USART2Com_TX_PIN & 0x07)*4));
    USART2Com_TX_GPIOX->AFR[USART2Com_TX_PIN>>3] |= USART2Com_TX_AFSEL << ((USART2Com_TX_PIN&0x07)*4);
    USART2Com_TX_GPIOX->MODER &= ~(3 << (USART2Com_TX_PIN*2));
    USART2Com_TX_GPIOX->MODER |= USART2Com_TX_PIN_MODE << (USART2Com_TX_PIN*2);
    USART2Com_TX_GPIOX->OTYPER &= ~(1 << USART2Com_TX_PIN);
    USART2Com_TX_GPIOX->OTYPER |= USART2Com_TX_PIN_TYPE << USART2Com_TX_PIN;
    USART2Com_TX_GPIOX->OSPEEDR &= ~(3 << (USART2Com_TX_PIN*2));
    USART2Com_TX_GPIOX->OSPEEDR |= USART2Com_TX_PIN_SPEED << (USART2Com_TX_PIN*2);
    USART2Com_TX_GPIOX->PUPDR &= ~(3 << (USART2Com_TX_PIN*2));
    USART2Com_TX_GPIOX->PUPDR |= USART2Com_TX_PIN_PULL << (USART2Com_TX_PIN*2);
    
    USART2Com_RX_GPIOX->AFR[USART2Com_RX_PIN>>3] &= ~(0xf << ((USART2Com_RX_PIN & 0x07)*4));
    USART2Com_RX_GPIOX->AFR[USART2Com_RX_PIN>>3] |= USART2Com_RX_AFSEL << ((USART2Com_RX_PIN&0x07)*4);
    USART2Com_RX_GPIOX->MODER &= ~(3 << (USART2Com_RX_PIN*2));
    USART2Com_RX_GPIOX->MODER |= USART2Com_RX_PIN_MODE << (USART2Com_RX_PIN*2);
    USART2Com_RX_GPIOX->OTYPER &= ~(1 << USART2Com_RX_PIN);
    USART2Com_RX_GPIOX->OTYPER |= USART2Com_RX_PIN_TYPE << USART2Com_RX_PIN;
    USART2Com_RX_GPIOX->OSPEEDR &= ~(3 << (USART2Com_RX_PIN*2));
    USART2Com_RX_GPIOX->OSPEEDR |= USART2Com_RX_PIN_SPEED << (USART2Com_RX_PIN*2);
    USART2Com_RX_GPIOX->PUPDR &= ~(3 << (USART2Com_RX_PIN*2));
    USART2Com_RX_GPIOX->PUPDR |= USART2Com_RX_PIN_PULL << (USART2Com_RX_PIN*2);
    
    USART2Com->CR1 = 0;
    USART2Com->CR2 = 0;
    USART2Com->CR1 |= WORD_LENGTH_8;
    USART2Com->CR2 |= STOP_1BIT;
    //MacCom->CR1 |= PARITY_EN;          
    //MacCom->CR1 |= PARITY_EVEN;        
    //MacCom->BRR = BAUD_9600;           
    USART2Com->BRR = BAUD_38400;
    NVIC_TEMP.NVIC_IRQChannel = USART2Com_IRQ;		            
	NVIC_TEMP.NVIC_IRQChannelPriority = USART2Com_PRIORITY;		
	NVIC_TEMP.NVIC_IRQChannelCmd = ENABLE;			            
	NVIC_Init(&NVIC_TEMP);
    
    USART2Com_RXINT_EN();                 
    USART2Com_TXEN();
    USART2Com_RXEN();
    USART2Com_EN();
    
}


void USART1_Com_Init(void)
{
    NVIC_InitTypeDef  NVIC_TEMP;
    
    RCC->GPIO_CLKREG |= USART1Com_GPIO_CLOCK_EN;
    RCC->USART1Com_CLKREG |= USART1Com_CLOCK_EN;
    
    
    USART1Com_TX_GPIOX->AFR[USART1Com_TX_PIN>>3] &= ~(0xf << ((USART1Com_TX_PIN & 0x07)*4));
    USART1Com_TX_GPIOX->AFR[USART1Com_TX_PIN>>3] |= USART1Com_TX_AFSEL << ((USART1Com_TX_PIN&0x07)*4);
    USART1Com_TX_GPIOX->MODER &= ~(3 << (USART1Com_TX_PIN*2));
    USART1Com_TX_GPIOX->MODER |= USART1Com_TX_PIN_MODE << (USART1Com_TX_PIN*2);
    USART1Com_TX_GPIOX->OTYPER &= ~(1 << USART1Com_TX_PIN);
    USART1Com_TX_GPIOX->OTYPER |= USART1Com_TX_PIN_TYPE << USART1Com_TX_PIN;
    USART1Com_TX_GPIOX->OSPEEDR &= ~(3 << (USART1Com_TX_PIN*2));
    USART1Com_TX_GPIOX->OSPEEDR |= USART1Com_TX_PIN_SPEED << (USART1Com_TX_PIN*2);
    USART1Com_TX_GPIOX->PUPDR &= ~(3 << (USART1Com_TX_PIN*2));
    USART1Com_TX_GPIOX->PUPDR |= USART1Com_TX_PIN_PULL << (USART1Com_TX_PIN*2);
    
    USART1Com_RX_GPIOX->AFR[USART1Com_RX_PIN>>3] &= ~(0xf << ((USART1Com_RX_PIN & 0x07)*4));
    USART1Com_RX_GPIOX->AFR[USART1Com_RX_PIN>>3] |= USART1Com_RX_AFSEL << ((USART1Com_RX_PIN&0x07)*4);
    USART1Com_RX_GPIOX->MODER &= ~(3 << (USART1Com_RX_PIN*2));
    USART1Com_RX_GPIOX->MODER |= USART1Com_RX_PIN_MODE << (USART1Com_RX_PIN*2);
    USART1Com_RX_GPIOX->OTYPER &= ~(1 << USART1Com_RX_PIN);
    USART1Com_RX_GPIOX->OTYPER |= USART1Com_RX_PIN_TYPE << USART1Com_RX_PIN;
    USART1Com_RX_GPIOX->OSPEEDR &= ~(3 << (USART1Com_RX_PIN*2));
    USART1Com_RX_GPIOX->OSPEEDR |= USART1Com_RX_PIN_SPEED << (USART1Com_RX_PIN*2);
    USART1Com_RX_GPIOX->PUPDR &= ~(3 << (USART1Com_RX_PIN*2));
    USART1Com_RX_GPIOX->PUPDR |= USART1Com_RX_PIN_PULL << (USART1Com_RX_PIN*2);
    
    USART1Com->CR1 = 0;
    USART1Com->CR2 = 0;
    USART1Com->CR1 |= WORD_LENGTH_9;
    USART1Com->CR2 |= STOP_1BIT;
    USART1Com->CR1 |= PARITY_EN;
    USART1Com->CR1 |= PARITY_EVEN;
    USART1Com->BRR = BAUD_57600;
    
    
    NVIC_TEMP.NVIC_IRQChannel = USART1Com_IRQ;		            
	NVIC_TEMP.NVIC_IRQChannelPriority = USART1Com_PRIORITY;		
	NVIC_TEMP.NVIC_IRQChannelCmd = ENABLE;			            
	NVIC_Init(&NVIC_TEMP);
    
    USART1Com_RXINT_EN();
    USART1Com_TXEN();
    USART1Com_RXEN();
}

